README.md
courier.go
go.mod
go.sum
send.go
send_test.go

Update the Send function signature to include a context, and strict parameters. Add a test.  Currently packaged for expel-io.
> Fix [#1]()

Package courier

---

messages.go
messages_test.go

Add messages api

---

README.md
courier.go

> Update README to reflect a working example and APIs covered so far
> None

Update README and baseUri

---

README.md
messages.go
messages_test.go
send.go
send_test.go

Messages api

---

CHANGELOG.md
v2/automations.go
v2/automations_test.go
v2/courier.go
v2/examples/automations/invoke.go
v2/examples/automations/invoke_template.go

Adds Automation API with tests and examples
None

C-2621: Add Automations API

---

CHANGELOG.md
v2/brands.go
v2/brands_test.go
v2/courier.go
v2/examples/brands/delete_brand.go
v2/examples/brands/get_brand.go
v2/examples/brands/get_brands.go
v2/examples/brands/post_brand.go
v2/examples/brands/put_brand.go

> Add support for brands API
> None

Add Brands API

---

CHANGELOG.md
v2/courier.go
v2/examples/notifications/cancel_notification_submission.go
v2/examples/notifications/get_notification_content.go
v2/examples/notifications/get_notification_draft_content.go
v2/examples/notifications/get_notification_submission_checks.go
v2/examples/notifications/get_notifications.go
v2/examples/notifications/post_notification_draft_variations.go
v2/examples/notifications/post_notification_varations.go
v2/examples/notifications/put_notification_submission_checks.go
v2/notifications.go
v2/notifications_test.go

Add support for Notifications API
> Fix [#1]()

C-3748: Add Notifications API

---

CHANGELOG.md
v2/bulk.go
v2/bulk_test.go
v2/courier.go
v2/examples/bulk/create_job.go
v2/examples/bulk/get_job.go
v2/examples/bulk/get_job_users.go
v2/examples/bulk/ingest_job.go
v2/examples/bulk/run_job.go

Adds support for Bulk API
> Fix [#1]()

C-4962: Add support for bulk API

---

README.md

[C-5280] - updates README with V2 call.

---

README.md

- Fixes broken documentation links
> Fix [#1]()

[JFDI] Fixing dead links in the readme

---

v2/examples/send/send_message_timeout.go
v2/send_test.go

- Adds test for new timeout prop
- Adds example
> Fix [#1]()

[C-5501] Alexander/c 5501 Test send_message with timeout prop

---

README.md
go.sum
v2/api.go
v2/examples/send/send_message_idempotent.go
v2/send.go
v2/send_test.go

Add support for idempotent messages by using go options
> Fix [#1]()

Add support for idempotent messages

---

README.md
v2/audiences.go
v2/audiences_test.go

Adds audiences support to Go package

[C-5559] adds audiences support

---

v2/examples/send/send_message_with_metadata.go
v2/send_test.go

Support metadata.trace_id by adding an example and a new test
> Fix [#1]()

Support metadata.trace_id

---

README.md
v2/audiences.go
v2/audiences_test.go

Add delete audience and update docs while at it
> Fix [#1]()

Add delete audience and update docs while at it

---

v2/examples/send/send_message_with_metadata.go

[C-5441] Update metadata example with tags and utm

---

v2/examples/send/send_message_with_granular_metadata.go
v2/send_test.go

- Adding example of granular UTM

Added test and example for sending granular metadata

---

v2/examples/send/send_message_timeout.go

- Added a complete example of `timeout`
> Fix [#1]()

Added complete example of timeout

---

v2/courier.go
v2/examples/send/send_message_idempotent.go

Fix Idempotent Example 
> Fix [#1]()

Update idempotent example

---

v2/courier.go

Release minor version upgrade so type changes are picked up (hypothesis)
> Fix [#1]()

Release a minor version

---

CHANGELOG.md
README.md
v2/audit_events.go
v2/audit_events_test.go
v2/courier.go
v2/examples/audit-events/get_audit_event.go
v2/examples/audit-events/list_audit_events.go
v2/send_test.go

[C-6477] Audit Events

---

CHANGELOG.md
README.md
messages.go
messages_test.go
v2/courier.go

- adds support for cancel message api

[C-9812] - add support for cancel message api

---

v2/messages.go

Remove confusing code comment in messages.go and add missing attribute

---

CHANGELOG.md
v2/courier.go

Bump version

---

CHANGELOG.md
README.md
v2/accounts.go
v2/accounts_test.go
v2/courier.go
v2/messages.go

Add accounts API

---

CHANGELOG.md
v2/accounts.go
v2/accounts_test.go
v2/courier.go

Add pagination attributes for accounts
> Fix [#1]()

Add pagination attributes for accounts

---

v2/tenants.go
v2/tenants_test.go

Changes `accounts` endpoint to `tenants`
> Fix [#1]()

[C-10108] changes accounts endpoint to tenants

---

CHANGELOG.md
courier.go
v2/courier.go

3.1.0 Includes adds support for the cancel message endpoint
N/A

Set user agent version, Update Changelog

---

README.md

This adjusts the `README.md` to reflect the latest API, including the new `option` import path, as well as a revised union construction example.

Update README.md to match latest API
